---
- name: launch cf
  cloudformation: 
    stack_name: piedpiper
    state: present
    region: us-east-1
    template: "/opt/ansible/playbooks/automation/aws/piedpiper_template.json"
    template_parameters: 
      KeyName: "{{keyname}}"
      InstanceType: "{{instancetype}}"
    register: stack
  - name: show stack outputs
    debug: msg="My stack outputs are {{stack.stack_outputs}}"
